// ============================================================
// ZeParty Admin Portal — World Countries & Flag Dataset
// ISO 3166-1 alpha-2 complete country directory
// ============================================================

/**
 * Standard 3-letter short name mapping for popular countries
 */
const SHORT_NAME_MAP = {
  US: 'USA',
  GB: 'UK',
  UK: 'UK',
  PK: 'PAK',
  AU: 'AUS',
  AE: 'UAE',
  SA: 'KSA',
  CA: 'CAN',
  DE: 'GER',
  FR: 'FRA',
  JP: 'JPN',
  CN: 'CHN',
  IN: 'IND',
  BR: 'BRA',
  MX: 'MEX',
  EG: 'EGY',
  ID: 'IDN',
  AF: 'AFG',
  AL: 'ALB',
  DZ: 'ALG',
  AD: 'AND',
  AO: 'ANG',
  AR: 'ARG',
  AM: 'ARM',
  AT: 'AUT',
  AZ: 'AZE',
  BS: 'BAH',
  BH: 'BHR',
  BD: 'BAN',
  BY: 'BLR',
  BE: 'BEL',
  BO: 'BOL',
  BA: 'BIH',
  BW: 'BOT',
  BN: 'BRU',
  BG: 'BUL',
  KH: 'CAM',
  CM: 'CMR',
  CL: 'CHI',
  CO: 'COL',
  CR: 'CRC',
  HR: 'CRO',
  CU: 'CUB',
  CY: 'CYP',
  CZ: 'CZE',
  DK: 'DEN',
  DO: 'DOM',
  EC: 'ECU',
  SV: 'ESA',
  EE: 'EST',
  ET: 'ETH',
  FI: 'FIN',
  GE: 'GEO',
  GH: 'GHA',
  GR: 'GRE',
  GT: 'GUA',
  HT: 'HAI',
  HN: 'HON',
  HK: 'HKG',
  HU: 'HUN',
  IS: 'ISL',
  IR: 'IRI',
  IQ: 'IRQ',
  IE: 'IRL',
  IL: 'ISR',
  IT: 'ITA',
  JM: 'JAM',
  JO: 'JOR',
  KZ: 'KAZ',
  KE: 'KEN',
  KW: 'KUW',
  KG: 'KGZ',
  LA: 'LAO',
  LV: 'LAT',
  LB: 'LBN',
  LY: 'LBY',
  LT: 'LTU',
  LU: 'LUX',
  MY: 'MAS',
  MV: 'MDV',
  ML: 'MLI',
  MT: 'MLT',
  MA: 'MAR',
  MN: 'MGL',
  ME: 'MNE',
  NP: 'NEP',
  NL: 'NED',
  NZ: 'NZL',
  NO: 'NOR',
  OM: 'OMA',
  PA: 'PAN',
  PY: 'PAR',
  PE: 'PER',
  PH: 'PHI',
  PL: 'POL',
  PT: 'POR',
  QA: 'QAT',
  RO: 'ROU',
  RU: 'RUS',
  SN: 'SEN',
  RS: 'SRB',
  SG: 'SGP',
  SK: 'SVK',
  SI: 'SLO',
  ZA: 'RSA',
  KR: 'KOR',
  ES: 'ESP',
  LK: 'SRI',
  SD: 'SUD',
  SE: 'SWE',
  CH: 'SUI',
  SY: 'SYR',
  TW: 'TPE',
  TH: 'THA',
  TN: 'TUN',
  TR: 'TUR',
  UG: 'UGA',
  UA: 'UKR',
  UY: 'URU',
  UZ: 'UZB',
  VE: 'VEN',
  VN: 'VIE',
  YE: 'YEM',
  ZM: 'ZAM',
  ZW: 'ZIM',
};

/**
 * Get 3-letter short country name (e.g., PAK, AUS, USA, UAE, KSA, GER, FRA)
 */
export function getCountryShortName(code) {
  if (!code || code === 'All' || code === 'GLOBAL' || code === 'Global') return 'Global';
  const upper = code.toUpperCase().trim();
  if (SHORT_NAME_MAP[upper]) return SHORT_NAME_MAP[upper];
  return upper;
}

/**
 * Get full country name
 */
export function getCountryName(code) {
  if (!code || code === 'All' || code === 'GLOBAL' || code === 'Global') return 'Global';
  const found = ALL_COUNTRIES.find((c) => c.code.toLowerCase() === code.toLowerCase());
  return found ? found.name : code;
}

export const GLOBAL_COUNTRY_OPTION = {
  code: 'All',
  name: 'Global',
  shortName: 'Global'
};

export const ALL_COUNTRIES = [
  GLOBAL_COUNTRY_OPTION,
  { code: 'AF', name: 'Afghanistan', shortName: 'AFG' },
  { code: 'AL', name: 'Albania', shortName: 'ALB' },
  { code: 'DZ', name: 'Algeria', shortName: 'ALG' },
  { code: 'AD', name: 'Andorra', shortName: 'AND' },
  { code: 'AO', name: 'Angola', shortName: 'ANG' },
  { code: 'AG', name: 'Antigua and Barbuda', shortName: 'ATG' },
  { code: 'AR', name: 'Argentina', shortName: 'ARG' },
  { code: 'AM', name: 'Armenia', shortName: 'ARM' },
  { code: 'AU', name: 'Australia', shortName: 'AUS' },
  { code: 'AT', name: 'Austria', shortName: 'AUT' },
  { code: 'AZ', name: 'Azerbaijan', shortName: 'AZE' },
  { code: 'BS', name: 'Bahamas', shortName: 'BAH' },
  { code: 'BH', name: 'Bahrain', shortName: 'BHR' },
  { code: 'BD', name: 'Bangladesh', shortName: 'BAN' },
  { code: 'BB', name: 'Barbados', shortName: 'BAR' },
  { code: 'BY', name: 'Belarus', shortName: 'BLR' },
  { code: 'BE', name: 'Belgium', shortName: 'BEL' },
  { code: 'BZ', name: 'Belize', shortName: 'BIZ' },
  { code: 'BJ', name: 'Benin', shortName: 'BEN' },
  { code: 'BT', name: 'Bhutan', shortName: 'BHU' },
  { code: 'BO', name: 'Bolivia', shortName: 'BOL' },
  { code: 'BA', name: 'Bosnia and Herzegovina', shortName: 'BIH' },
  { code: 'BW', name: 'Botswana', shortName: 'BOT' },
  { code: 'BR', name: 'Brazil', shortName: 'BRA' },
  { code: 'BN', name: 'Brunei', shortName: 'BRU' },
  { code: 'BG', name: 'Bulgaria', shortName: 'BUL' },
  { code: 'BF', name: 'Burkina Faso', shortName: 'BUR' },
  { code: 'BI', name: 'Burundi', shortName: 'BDI' },
  { code: 'KH', name: 'Cambodia', shortName: 'CAM' },
  { code: 'CM', name: 'Cameroon', shortName: 'CMR' },
  { code: 'CA', name: 'Canada', shortName: 'CAN' },
  { code: 'CV', name: 'Cape Verde', shortName: 'CPV' },
  { code: 'CF', name: 'Central African Republic', shortName: 'CTA' },
  { code: 'TD', name: 'Chad', shortName: 'CHA' },
  { code: 'CL', name: 'Chile', shortName: 'CHI' },
  { code: 'CN', name: 'China', shortName: 'CHN' },
  { code: 'CO', name: 'Colombia', shortName: 'COL' },
  { code: 'KM', name: 'Comoros', shortName: 'COM' },
  { code: 'CG', name: 'Congo', shortName: 'CGO' },
  { code: 'CD', name: 'Congo (DRC)', shortName: 'COD' },
  { code: 'CR', name: 'Costa Rica', shortName: 'CRC' },
  { code: 'HR', name: 'Croatia', shortName: 'CRO' },
  { code: 'CU', name: 'Cuba', shortName: 'CUB' },
  { code: 'CY', name: 'Cyprus', shortName: 'CYP' },
  { code: 'CZ', name: 'Czech Republic', shortName: 'CZE' },
  { code: 'DK', name: 'Denmark', shortName: 'DEN' },
  { code: 'DJ', name: 'Djibouti', shortName: 'DJI' },
  { code: 'DM', name: 'Dominica', shortName: 'DMA' },
  { code: 'DO', name: 'Dominican Republic', shortName: 'DOM' },
  { code: 'EC', name: 'Ecuador', shortName: 'ECU' },
  { code: 'EG', name: 'Egypt', shortName: 'EGY' },
  { code: 'SV', name: 'El Salvador', shortName: 'ESA' },
  { code: 'GQ', name: 'Equatorial Guinea', shortName: 'EQG' },
  { code: 'ER', name: 'Eritrea', shortName: 'ERI' },
  { code: 'EE', name: 'Estonia', shortName: 'EST' },
  { code: 'SZ', name: 'Eswatini', shortName: 'SWZ' },
  { code: 'ET', name: 'Ethiopia', shortName: 'ETH' },
  { code: 'FJ', name: 'Fiji', shortName: 'FIJ' },
  { code: 'FI', name: 'Finland', shortName: 'FIN' },
  { code: 'FR', name: 'France', shortName: 'FRA' },
  { code: 'GA', name: 'Gabon', shortName: 'GAB' },
  { code: 'GM', name: 'Gambia', shortName: 'GAM' },
  { code: 'GE', name: 'Georgia', shortName: 'GEO' },
  { code: 'DE', name: 'Germany', shortName: 'GER' },
  { code: 'GH', name: 'Ghana', shortName: 'GHA' },
  { code: 'GR', name: 'Greece', shortName: 'GRE' },
  { code: 'GD', name: 'Grenada', shortName: 'GRN' },
  { code: 'GT', name: 'Guatemala', shortName: 'GUA' },
  { code: 'GN', name: 'Guinea', shortName: 'GUI' },
  { code: 'GW', name: 'Guinea-Bissau', shortName: 'GBS' },
  { code: 'GY', name: 'Guyana', shortName: 'GUY' },
  { code: 'HT', name: 'Haiti', shortName: 'HAI' },
  { code: 'HN', name: 'Honduras', shortName: 'HON' },
  { code: 'HK', name: 'Hong Kong', shortName: 'HKG' },
  { code: 'HU', name: 'Hungary', shortName: 'HUN' },
  { code: 'IS', name: 'Iceland', shortName: 'ISL' },
  { code: 'IN', name: 'India', shortName: 'IND' },
  { code: 'ID', name: 'Indonesia', shortName: 'IDN' },
  { code: 'IR', name: 'Iran', shortName: 'IRI' },
  { code: 'IQ', name: 'Iraq', shortName: 'IRQ' },
  { code: 'IE', name: 'Ireland', shortName: 'IRL' },
  { code: 'IL', name: 'Israel', shortName: 'ISR' },
  { code: 'IT', name: 'Italy', shortName: 'ITA' },
  { code: 'CI', name: 'Ivory Coast', shortName: 'CIV' },
  { code: 'JM', name: 'Jamaica', shortName: 'JAM' },
  { code: 'JP', name: 'Japan', shortName: 'JPN' },
  { code: 'JO', name: 'Jordan', shortName: 'JOR' },
  { code: 'KZ', name: 'Kazakhstan', shortName: 'KAZ' },
  { code: 'KE', name: 'Kenya', shortName: 'KEN' },
  { code: 'KW', name: 'Kuwait', shortName: 'KUW' },
  { code: 'KG', name: 'Kyrgyzstan', shortName: 'KGZ' },
  { code: 'LA', name: 'Laos', shortName: 'LAO' },
  { code: 'LV', name: 'Latvia', shortName: 'LAT' },
  { code: 'LB', name: 'Lebanon', shortName: 'LBN' },
  { code: 'LS', name: 'Lesotho', shortName: 'LES' },
  { code: 'LR', name: 'Liberia', shortName: 'LBR' },
  { code: 'LY', name: 'Libya', shortName: 'LBY' },
  { code: 'LI', name: 'Liechtenstein', shortName: 'LIE' },
  { code: 'LT', name: 'Lithuania', shortName: 'LTU' },
  { code: 'LU', name: 'Luxembourg', shortName: 'LUX' },
  { code: 'MO', name: 'Macau', shortName: 'MAC' },
  { code: 'MG', name: 'Madagascar', shortName: 'MAD' },
  { code: 'MW', name: 'Malawi', shortName: 'MAW' },
  { code: 'MY', name: 'Malaysia', shortName: 'MAS' },
  { code: 'MV', name: 'Maldives', shortName: 'MDV' },
  { code: 'ML', name: 'Mali', shortName: 'MLI' },
  { code: 'MT', name: 'Malta', shortName: 'MLT' },
  { code: 'MR', name: 'Mauritania', shortName: 'MTN' },
  { code: 'MU', name: 'Mauritius', shortName: 'MRI' },
  { code: 'MX', name: 'Mexico', shortName: 'MEX' },
  { code: 'MD', name: 'Moldova', shortName: 'MDA' },
  { code: 'MC', name: 'Monaco', shortName: 'MON' },
  { code: 'MN', name: 'Mongolia', shortName: 'MGL' },
  { code: 'ME', name: 'Montenegro', shortName: 'MNE' },
  { code: 'MA', name: 'Morocco', shortName: 'MAR' },
  { code: 'MZ', name: 'Mozambique', shortName: 'MOZ' },
  { code: 'MM', name: 'Myanmar', shortName: 'MYA' },
  { code: 'NA', name: 'Namibia', shortName: 'NAM' },
  { code: 'NP', name: 'Nepal', shortName: 'NEP' },
  { code: 'NL', name: 'Netherlands', shortName: 'NED' },
  { code: 'NZ', name: 'New Zealand', shortName: 'NZL' },
  { code: 'NI', name: 'Nicaragua', shortName: 'NCA' },
  { code: 'NE', name: 'Niger', shortName: 'NIG' },
  { code: 'NG', name: 'Nigeria', shortName: 'NGR' },
  { code: 'KP', name: 'North Korea', shortName: 'PRK' },
  { code: 'MK', name: 'North Macedonia', shortName: 'MKD' },
  { code: 'NO', name: 'Norway', shortName: 'NOR' },
  { code: 'OM', name: 'Oman', shortName: 'OMA' },
  { code: 'PK', name: 'Pakistan', shortName: 'PAK' },
  { code: 'PS', name: 'Palestine', shortName: 'PLE' },
  { code: 'PA', name: 'Panama', shortName: 'PAN' },
  { code: 'PG', name: 'Papua New Guinea', shortName: 'PNG' },
  { code: 'PY', name: 'Paraguay', shortName: 'PAR' },
  { code: 'PE', name: 'Peru', shortName: 'PER' },
  { code: 'PH', name: 'Philippines', shortName: 'PHI' },
  { code: 'PL', name: 'Poland', shortName: 'POL' },
  { code: 'PT', name: 'Portugal', shortName: 'POR' },
  { code: 'QA', name: 'Qatar', shortName: 'QAT' },
  { code: 'RO', name: 'Romania', shortName: 'ROU' },
  { code: 'RU', name: 'Russia', shortName: 'RUS' },
  { code: 'RW', name: 'Rwanda', shortName: 'RWA' },
  { code: 'SA', name: 'Saudi Arabia', shortName: 'KSA' },
  { code: 'SN', name: 'Senegal', shortName: 'SEN' },
  { code: 'RS', name: 'Serbia', shortName: 'SRB' },
  { code: 'SG', name: 'Singapore', shortName: 'SGP' },
  { code: 'SK', name: 'Slovakia', shortName: 'SVK' },
  { code: 'SI', name: 'Slovenia', shortName: 'SLO' },
  { code: 'SO', name: 'Somalia', shortName: 'SOM' },
  { code: 'ZA', name: 'South Africa', shortName: 'RSA' },
  { code: 'KR', name: 'South Korea', shortName: 'KOR' },
  { code: 'SS', name: 'South Sudan', shortName: 'SSD' },
  { code: 'ES', name: 'Spain', shortName: 'ESP' },
  { code: 'LK', name: 'Sri Lanka', shortName: 'SRI' },
  { code: 'SD', name: 'Sudan', shortName: 'SUD' },
  { code: 'SE', name: 'Sweden', shortName: 'SWE' },
  { code: 'CH', name: 'Switzerland', shortName: 'SUI' },
  { code: 'SY', name: 'Syria', shortName: 'SYR' },
  { code: 'TW', name: 'Taiwan', shortName: 'TPE' },
  { code: 'TJ', name: 'Tajikistan', shortName: 'TJK' },
  { code: 'TZ', name: 'Tanzania', shortName: 'TAN' },
  { code: 'TH', name: 'Thailand', shortName: 'THA' },
  { code: 'TL', name: 'Timor-Leste', shortName: 'TLS' },
  { code: 'TG', name: 'Togo', shortName: 'TOG' },
  { code: 'TT', name: 'Trinidad and Tobago', shortName: 'TTO' },
  { code: 'TN', name: 'Tunisia', shortName: 'TUN' },
  { code: 'TR', name: 'Turkey', shortName: 'TUR' },
  { code: 'TM', name: 'Turkmenistan', shortName: 'TKM' },
  { code: 'UG', name: 'Uganda', shortName: 'UGA' },
  { code: 'UA', name: 'Ukraine', shortName: 'UKR' },
  { code: 'AE', name: 'United Arab Emirates', shortName: 'UAE' },
  { code: 'GB', name: 'United Kingdom', shortName: 'UK' },
  { code: 'US', name: 'United States', shortName: 'USA' },
  { code: 'UY', name: 'Uruguay', shortName: 'URU' },
  { code: 'UZ', name: 'Uzbekistan', shortName: 'UZB' },
  { code: 'VE', name: 'Venezuela', shortName: 'VEN' },
  { code: 'VN', name: 'Vietnam', shortName: 'VIE' },
  { code: 'YE', name: 'Yemen', shortName: 'YEM' },
  { code: 'ZM', name: 'Zambia', shortName: 'ZAM' },
  { code: 'ZW', name: 'Zimbabwe', shortName: 'ZIM' }
];
